<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OpenWSR.NetCdf\OpenWSR.NetCdf.csproj" />
    <ProjectReference Include="..\OpenWSR.Nexrad\OpenWSR.Nexrad.csproj" />
    <ProjectReference Include="..\OpenWSR.Geo\OpenWSR.Geo.csproj" />
    <ProjectReference Include="..\OpenWSR.Grib2\OpenWSR.Grib2.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.102.1" />
    <PackageReference Include="Serilog" Version="4.4.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\nexrad-sites.csv" />
  </ItemGroup>

</Project>
